"""Editor playback state tests split into behavior-focused companions."""

from . import test_editor_playback_state_cursor as cursor_cases
from . import test_editor_playback_state_playback as playback_cases
from . import test_editor_playback_state_session as session_cases

test_is_busy_includes_playback_preparation = session_cases.test_is_busy_includes_playback_preparation
test_note_load_reset_clears_note_specific_session_state = (
    session_cases.test_note_load_reset_clears_note_specific_session_state
)
test_stale_playback_segment_completion_is_ignored_and_cleaned = (
    session_cases.test_stale_playback_segment_completion_is_ignored_and_cleaned
)
test_html_playback_request_updates_session_without_native_segment = (
    playback_cases.test_html_playback_request_updates_session_without_native_segment
)
test_late_html_playback_request_is_ignored_after_editor_note_is_cleared = (
    playback_cases.test_late_html_playback_request_is_ignored_after_editor_note_is_cleared
)
test_native_selected_playback_renders_segment_from_cursor_to_selection_end = (
    playback_cases.test_native_selected_playback_renders_segment_from_cursor_to_selection_end
)
test_playback_request_reports_missing_referenced_media_with_media_code = (
    playback_cases.test_playback_request_reports_missing_referenced_media_with_media_code
)
test_post_edit_playback_request_does_not_replace_status_while_analysis_is_busy = (
    playback_cases.test_post_edit_playback_request_does_not_replace_status_while_analysis_is_busy
)
test_html_cursor_restart_intent_does_not_start_native_playback = (
    cursor_cases.test_html_cursor_restart_intent_does_not_start_native_playback
)
test_late_cursor_intent_is_ignored_after_editor_note_is_cleared = (
    cursor_cases.test_late_cursor_intent_is_ignored_after_editor_note_is_cleared
)
test_native_cursor_restart_intent_keeps_selected_end_boundary = (
    cursor_cases.test_native_cursor_restart_intent_keeps_selected_end_boundary
)
