"""Architecture contracts for shared import-safe modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

CORE_CONTRACTS: dict[str, ModuleContract] = {
    "_version": contract("_version", layer=Layer.IMPORT_SAFE_CORE),
    "audio_deps": contract("audio_deps", layer=Layer.IMPORT_SAFE_CORE),
    "audio_formats": contract("audio_formats", layer=Layer.IMPORT_SAFE_CORE),
    "config_migration": contract(
        "config_migration",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_size_reduction",
            "dpdfnet_settings",
            "editor_button_visibility",
            "editor_history_settings",
        ),
    ),
    "contracts_generated": contract(
        "contracts_generated",
        layer=Layer.IMPORT_SAFE_CORE,
        notes="Generated quicktype DTOs for owned JSON bridge contracts.",
    ),
    "editor_button_visibility": contract(
        "editor_button_visibility",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "editor_history_settings": contract("editor_history_settings", layer=Layer.IMPORT_SAFE_CORE),
    "db_helpers": contract(
        "db_helpers",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_side_effects=(SideEffect.DB_ACCESS,),
    ),
    "diagnostics": contract(
        "diagnostics",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_processor",
            "audio_tools",
            "error_codes",
            "external_command_text",
            "permission_guidance",
            "runtime_manager",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "diagnostics_runtime": contract(
        "diagnostics_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("diagnostics_runtime_json", "diagnostics_runtime_storage"),
        notes="Runtime support diagnostics, breadcrumbs, exception hooks, and crash/session files.",
    ),
    "diagnostics_runtime_json": contract("diagnostics_runtime_json", layer=Layer.IMPORT_SAFE_CORE),
    "diagnostics_runtime_storage": contract(
        "diagnostics_runtime_storage",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("diagnostics_runtime_json",),
    ),
    "dpdfnet_settings": contract("dpdfnet_settings", layer=Layer.IMPORT_SAFE_CORE),
    "error_codes": contract("error_codes", layer=Layer.IMPORT_SAFE_CORE),
    "errors": contract("errors", layer=Layer.IMPORT_SAFE_CORE),
    "external_links": contract(
        "external_links",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors", "file_reveal"),
    ),
    "external_command_text": contract("external_command_text", layer=Layer.IMPORT_SAFE_CORE),
    "ffmpeg_defaults": contract("ffmpeg_defaults", layer=Layer.IMPORT_SAFE_CORE),
    "frontend_logs": contract(
        "frontend_logs",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("contracts_generated", "diagnostics_runtime"),
    ),
    "i18n": contract(
        "i18n",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_side_effects=(SideEffect.ANKI_IMPORTS_ANYWHERE,),
        allow_any_anki_imports=True,
        notes="Shared JSON catalog loader; imports Anki only inside active locale helpers.",
    ),
    "file_reveal": contract(
        "file_reveal",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors", "i18n"),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_POPEN,
            SideEffect.ANKI_IMPORTS_ANYWHERE,
        ),
        allow_any_anki_imports=True,
    ),
    "file_sharing": contract("file_sharing", layer=Layer.IMPORT_SAFE_CORE),
    "media_paths": contract(
        "media_paths",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("sound_refs",),
    ),
    "permission_guidance": contract("permission_guidance", layer=Layer.IMPORT_SAFE_CORE),
    "persistent_history": contract(
        "persistent_history",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state",),
        allowed_side_effects=(SideEffect.DB_ACCESS,),
        notes="Add-on-owned SQLite journal for persistent audio undo history.",
    ),
    "persistent_undo_chain": contract(
        "persistent_undo_chain",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors", "media_paths", "persistent_history", "sound_refs"),
        notes="Pure executable-chain planner for SQLite-backed persistent undo rows.",
    ),
    "prosody_analyzer": contract(
        "prosody_analyzer",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_state",
            "prosody_fallback",
            "prosody_praat",
            "prosody_types",
        ),
    ),
    "prosody_cache": contract(
        "prosody_cache",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "prosody_analyzer", "prosody_settings", "prosody_types"),
    ),
    "prosody_fallback": contract(
        "prosody_fallback",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_processor",
            "audio_state",
            "errors",
            "permission_guidance",
            "prosody_settings",
            "prosody_types",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "prosody_praat": contract(
        "prosody_praat",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_processor", "audio_state", "prosody_settings", "prosody_types"),
    ),
    "prosody_settings": contract(
        "prosody_settings",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "prosody_types"),
    ),
    "prosody_svg": contract(
        "prosody_svg",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("prosody_types",),
    ),
    "prosody_types": contract("prosody_types", layer=Layer.IMPORT_SAFE_CORE),
    "release_info": contract("release_info", layer=Layer.IMPORT_SAFE_CORE),
    "reviewer_audio_targets": contract("reviewer_audio_targets", layer=Layer.IMPORT_SAFE_CORE),
    "reviewer_template_filter": contract(
        "reviewer_template_filter",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("reviewer_audio_targets", "sound_refs"),
    ),
    "runtime_archive": contract(
        "runtime_archive",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("runtime_manifest",),
    ),
    "runtime_install": contract(
        "runtime_install",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "error_codes",
            "runtime_archive",
            "runtime_install_io",
            "runtime_lookup",
            "runtime_manifest",
            "runtime_paths",
            "runtime_platform",
            "runtime_state",
        ),
        allowed_side_effects=(
            SideEffect.THREAD_SPAWN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "runtime_install_io": contract(
        "runtime_install_io",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "runtime_archive",
            "runtime_manifest",
            "runtime_paths",
            "runtime_state",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "runtime_lookup": contract(
        "runtime_lookup",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "runtime_manifest",
            "runtime_paths",
            "runtime_platform",
            "runtime_state",
        ),
    ),
    "runtime_manager": contract(
        "runtime_manager",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "runtime_install",
            "runtime_lookup",
            "runtime_manifest",
            "runtime_paths",
            "runtime_platform",
            "runtime_state",
        ),
    ),
    "runtime_manifest": contract("runtime_manifest", layer=Layer.IMPORT_SAFE_CORE),
    "runtime_paths": contract(
        "runtime_paths",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("runtime_manifest",),
    ),
    "runtime_platform": contract("runtime_platform", layer=Layer.IMPORT_SAFE_CORE),
    "runtime_state": contract(
        "runtime_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("runtime_manifest", "runtime_paths"),
    ),
    "vendor_runtime": contract(
        "vendor_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("runtime_paths", "runtime_platform"),
    ),
    "settings_state": contract(
        "settings_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("contracts_generated", "ffmpeg_defaults"),
    ),
    "sound_refs": contract(
        "sound_refs",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors",),
    ),
    "support": contract("support", layer=Layer.IMPORT_SAFE_CORE, allowed_addon_deps=("i18n", "support_reporting")),
    "support_reporting": contract("support_reporting", layer=Layer.IMPORT_SAFE_CORE),
    "trigger_batch_adapter": contract(
        "trigger_batch_adapter",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operations",
            "audio_state",
            "batch_operation_processing",
            "batch_operation_types",
            "batch_operations",
            "batch_operations_helpers",
            "diagnostics_runtime",
            "error_codes",
            "errors",
            "media_paths",
            "sound_refs",
            "trigger_operation_support",
            "trigger_rules",
        ),
        notes="Headless one-note adapter reuses batch operation processors for trigger jobs.",
    ),
    "trigger_jobs": contract(
        "trigger_jobs",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("batch_operation_types", "trigger_rules", "trigger_state"),
        notes="Import-safe shared trigger job and execution result types.",
    ),
    "trigger_operation_support": contract(
        "trigger_operation_support",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_processor",
            "batch_operation_processing",
            "batch_operations_helpers",
            "prosody_cache",
        ),
        notes="Shared processing dependencies and HTML helpers for trigger adapters.",
    ),
    "trigger_preset_adapter": contract(
        "trigger_preset_adapter",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operations",
            "audio_processing_presets",
            "audio_state",
            "batch_operation_types",
            "batch_operations",
            "batch_operations_helpers",
            "batch_processing_presets",
            "diagnostics_runtime",
            "error_codes",
            "errors",
            "media_paths",
            "sound_refs",
            "trigger_operation_support",
            "trigger_rules",
        ),
        notes="Headless preset trigger adapter changes only trigger-specific field write semantics.",
    ),
    "trigger_rules": contract(
        "trigger_rules",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operation_params",
            "audio_operations",
            "audio_processing_presets",
            "errors",
            "sound_refs",
        ),
        notes="Import-safe trigger config model, validation, matching, and fingerprints.",
    ),
    "trigger_state": contract(
        "trigger_state",
        layer=Layer.IMPORT_SAFE_CORE,
        notes="JSON sidecar state model for latest-wins trigger scheduling.",
    ),
    "webview_bridge": contract("webview_bridge", layer=Layer.IMPORT_SAFE_CORE),
    "webview_shell": contract("webview_shell", layer=Layer.IMPORT_SAFE_CORE),
}
