"""Architecture contracts for editor runtime modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

EDITOR_CONTRACTS: dict[str, ModuleContract] = {
    "editor_actions": contract(
        "editor_actions",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_operation_params", "audio_operations", "audio_state"),
    ),
    "editor_analysis": contract(
        "editor_analysis",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "contracts_generated",
            "diagnostics_runtime",
            "editor_session",
            "errors",
            "i18n",
            "media_paths",
            "permission_guidance",
            "prosody_settings",
            "prosody_types",
            "sound_refs",
        ),
        allowed_side_effects=(
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
    ),
    "editor_bridge": contract(
        "editor_bridge",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("diagnostics_runtime", "editor_actions", "errors", "frontend_logs", "i18n"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_conversion": contract(
        "editor_conversion",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_formats",
            "audio_state",
            "editor_actions",
            "editor_session",
            "i18n",
        ),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_callbacks": contract(
        "editor_callbacks",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "audio_state",
            "editor_actions",
            "editor_analysis",
            "editor_bridge",
            "editor_dependencies",
            "editor_frontend_callbacks",
            "editor_history",
            "editor_playback",
            "editor_processing",
            "editor_recording",
            "editor_region_delete",
            "editor_runtime",
            "editor_session",
            "editor_settings_actions",
            "editor_sharing",
            "editor_split_defaults",
            "prosody_types",
        ),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_frontend": contract(
        "editor_frontend",
        layer=Layer.UI_ADAPTER,
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_frontend_callbacks": contract(
        "editor_frontend_callbacks",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("editor_dependencies", "editor_frontend"),
        allowed_side_effects=(
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
    ),
    "editor_dependencies": contract(
        "editor_dependencies",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "audio_recording",
            "editor_media",
            "editor_runtime",
            "file_sharing",
            "i18n",
            "prosody_cache",
            "support",
        ),
    ),
    "editor_history": contract(
        "editor_history",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("editor_session", "editor_status", "errors", "i18n", "media_paths", "sound_refs"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_media": contract(
        "editor_media",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("editor_session", "errors", "i18n", "media_paths", "sound_refs"),
    ),
    "editor_playback": contract(
        "editor_playback",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "diagnostics_runtime",
            "editor_session",
            "i18n",
            "media_paths",
            "permission_guidance",
            "prosody_types",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_processing": contract(
        "editor_processing",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_formats",
            "audio_state",
            "diagnostics_runtime",
            "editor_actions",
            "editor_conversion",
            "editor_processing_shared",
            "editor_special_transforms",
            "editor_session",
            "editor_status",
            "errors",
            "i18n",
            "media_paths",
            "permission_guidance",
            "prosody_settings",
            "sound_refs",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_processing_shared": contract(
        "editor_processing_shared",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("editor_session",),
    ),
    "editor_region_delete": contract(
        "editor_region_delete",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "diagnostics_runtime",
            "editor_region_delete_request",
            "editor_session",
            "editor_status",
            "errors",
            "i18n",
            "media_paths",
            "permission_guidance",
            "sound_refs",
        ),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_region_delete_request": contract(
        "editor_region_delete_request",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("editor_session", "i18n", "sound_refs"),
    ),
    "editor_recording": contract(
        "editor_recording",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_recording",
            "audio_state",
            "diagnostics_runtime",
            "editor_recording_frontend",
            "editor_session",
            "errors",
            "i18n",
            "permission_guidance",
            "prosody_settings",
            "prosody_types",
            "sound_refs",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_recording_frontend": contract(
        "editor_recording_frontend",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("contracts_generated", "editor_session", "prosody_types"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_session": contract(
        "editor_session",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state",),
    ),
    "editor_runtime": contract(
        "editor_runtime",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "editor_media",
            "editor_playback",
            "editor_session",
            "editor_status",
            "errors",
            "i18n",
            "media_paths",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "editor_settings_actions": contract(
        "editor_settings_actions",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("editor_runtime", "editor_session", "file_reveal", "i18n"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_status": contract(
        "editor_status",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_formats",
            "audio_state",
            "dpdfnet_settings",
            "editor_actions",
            "editor_session",
            "i18n",
        ),
    ),
    "editor_sharing": contract(
        "editor_sharing",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("diagnostics_runtime", "editor_actions"),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_special_transforms": contract(
        "editor_special_transforms",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_formats",
            "audio_state",
            "diagnostics_runtime",
            "editor_actions",
            "editor_processing_shared",
            "editor_session",
            "editor_status",
            "errors",
            "i18n",
            "media_paths",
            "permission_guidance",
            "prosody_settings",
            "sound_refs",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_split_defaults": contract(
        "editor_split_defaults",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("audio_operation_params", "i18n", "prosody_settings"),
    ),
    "editor_integration": contract(
        "editor_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "audio_state",
            "contracts_generated",
            "editor_actions",
            "editor_analysis",
            "editor_bridge",
            "editor_callbacks",
            "editor_dependencies",
            "editor_frontend",
            "editor_history",
            "editor_media",
            "editor_playback",
            "editor_processing",
            "editor_region_delete",
            "editor_runtime",
            "editor_session",
            "editor_settings_actions",
            "editor_status",
            "editor_split_defaults",
            "editor_ui",
            "errors",
            "file_reveal",
            "media_paths",
            "prosody_cache",
            "prosody_types",
            "sound_refs",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.GUI_HOOK_REGISTRATION,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_ui": contract("editor_ui", layer=Layer.IMPORT_SAFE_CORE, allowed_addon_deps=("i18n",)),
}
