"""Architecture contracts for editor runtime modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

EDITOR_CONTRACTS: dict[str, ModuleContract] = {
    "editor_actions": contract(
        "editor_actions",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_operations", "audio_state"),
    ),
    "editor_analysis": contract(
        "editor_analysis",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "contracts_generated",
            "editor_session",
            "errors",
            "prosody_types",
            "sound_refs",
        ),
        allowed_side_effects=(
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
    ),
    "editor_bridge": contract(
        "editor_bridge",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("contracts_generated", "editor_actions", "errors"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_callbacks": contract(
        "editor_callbacks",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "audio_state",
            "editor_actions",
            "editor_analysis",
            "editor_bridge",
            "editor_dependencies",
            "editor_frontend_callbacks",
            "editor_history",
            "editor_playback",
            "editor_processing",
            "editor_region_delete",
            "editor_runtime",
            "editor_session",
            "editor_settings_actions",
            "prosody_types",
        ),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_frontend": contract(
        "editor_frontend",
        layer=Layer.UI_ADAPTER,
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_frontend_callbacks": contract(
        "editor_frontend_callbacks",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("editor_dependencies", "editor_frontend"),
        allowed_side_effects=(
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
    ),
    "editor_dependencies": contract(
        "editor_dependencies",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "editor_media",
            "editor_runtime",
            "prosody_cache",
            "support",
        ),
    ),
    "editor_history": contract(
        "editor_history",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("editor_session", "errors", "sound_refs"),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_media": contract(
        "editor_media",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("editor_session", "errors", "sound_refs"),
    ),
    "editor_playback": contract(
        "editor_playback",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("audio_state", "editor_session", "prosody_types"),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_processing": contract(
        "editor_processing",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "editor_actions",
            "editor_session",
            "errors",
            "sound_refs",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_region_delete": contract(
        "editor_region_delete",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("audio_state", "editor_session", "errors", "sound_refs"),
        allowed_side_effects=(
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "editor_session": contract(
        "editor_session",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state",),
    ),
    "editor_runtime": contract(
        "editor_runtime",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "editor_media",
            "editor_playback",
            "editor_session",
            "errors",
            "sound_refs",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "editor_settings_actions": contract(
        "editor_settings_actions",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("file_reveal",),
        allowed_side_effects=(SideEffect.WEB_EVAL,),
    ),
    "editor_integration": contract(
        "editor_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processor",
            "audio_state",
            "contracts_generated",
            "editor_actions",
            "editor_analysis",
            "editor_bridge",
            "editor_callbacks",
            "editor_dependencies",
            "editor_frontend",
            "editor_history",
            "editor_media",
            "editor_playback",
            "editor_processing",
            "editor_region_delete",
            "editor_runtime",
            "editor_session",
            "editor_settings_actions",
            "editor_ui",
            "errors",
            "file_reveal",
            "prosody_cache",
            "prosody_types",
            "sound_refs",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.MEDIA_WRITE,
            SideEffect.THREAD_SPAWN,
            SideEffect.GUI_HOOK_REGISTRATION,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
        allow_any_anki_imports=True,
    ),
    "editor_ui": contract("editor_ui", layer=Layer.IMPORT_SAFE_CORE),
}
