"""Architecture contracts for audio core modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

AUDIO_CORE_CONTRACTS: dict[str, ModuleContract] = {
    "audio_operations": contract(
        "audio_operations",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "i18n"),
    ),
    "audio_operation_params": contract(
        "audio_operation_params",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operation_params_config",
            "audio_operation_params_normalize",
            "audio_operation_params_types",
        ),
    ),
    "audio_operation_params_config": contract(
        "audio_operation_params_config",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operation_params_types",
            "audio_pause_settings",
            "audio_size_reduction",
            "audio_state",
        ),
    ),
    "audio_operation_params_normalize": contract(
        "audio_operation_params_normalize",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_operation_params_types",
            "audio_pause_settings",
            "audio_size_reduction",
            "dpdfnet_settings",
        ),
    ),
    "audio_operation_params_types": contract(
        "audio_operation_params_types",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "audio_size_reduction": contract(
        "audio_size_reduction",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors",),
    ),
    "audio_pause_settings": contract("audio_pause_settings", layer=Layer.IMPORT_SAFE_CORE),
    "audio_processing_presets": contract(
        "audio_processing_presets",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_operation_params", "audio_operations"),
    ),
    "audio_processing_preset_runner": contract(
        "audio_processing_preset_runner",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_operation_params",
            "audio_operations",
            "audio_processing_presets",
            "audio_state",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "audio_pipeline": contract("audio_pipeline", layer=Layer.IMPORT_SAFE_CORE),
    "audio_artifacts": contract(
        "audio_artifacts",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_pipeline", "audio_state", "audio_tools", "errors"),
    ),
    "audio_commands": contract(
        "audio_commands",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands_runtime",
            "audio_formats",
            "audio_state",
            "audio_types",
            "errors",
            "ffmpeg_output_contracts",
        ),
    ),
    "audio_commands_runtime": contract(
        "audio_commands_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("ffmpeg_output_contracts",),
    ),
    "audio_export_types": contract(
        "audio_export_types",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "audio_export_planning": contract(
        "audio_export_planning",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_export_types",
            "batch_operation_types",
            "media_paths",
            "sound_refs",
        ),
    ),
    "audio_export_rendering": contract(
        "audio_export_rendering",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_commands", "ffmpeg_output_contracts"),
    ),
    "audio_external": contract(
        "audio_external",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_state",
            "audio_tools",
            "diagnostics_runtime",
            "errors",
            "external_command_text",
            "permission_guidance",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "audio_output_policy": contract(
        "audio_output_policy",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_external",
            "audio_formats",
            "audio_state",
            "audio_tools",
            "errors",
            "external_command_text",
            "permission_guidance",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "audio_noise_reduction": contract(
        "audio_noise_reduction",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_noise_reduction_bundled",
            "audio_output_policy",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "audio_noise_reduction_bundled": contract(
        "audio_noise_reduction_bundled",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_noise_reduction_telemetry",
            "audio_output_policy",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_noise_reduction_telemetry": contract(
        "audio_noise_reduction_telemetry",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("support",),
    ),
    "audio_pitch_hum": contract(
        "audio_pitch_hum",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_output_policy",
            "audio_pitch_hum_synthesis",
            "audio_pitch_hum_frames",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "external_command_text",
            "permission_guidance",
            "prosody_settings",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_pitch_hum_frames": contract(
        "audio_pitch_hum_frames",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "audio_pitch_hum_synthesis": contract(
        "audio_pitch_hum_synthesis",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_pitch_hum_frames",),
    ),
    "audio_pause_pipeline": contract(
        "audio_pause_pipeline",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_external",
            "audio_pause_pipeline_stage",
            "audio_pause_pipeline_steps",
            "audio_state",
            "audio_tools",
            "audio_types",
            "support",
        ),
    ),
    "audio_pause_pipeline_steps": contract(
        "audio_pause_pipeline_steps",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_external",
            "audio_pause_pipeline_detection",
            "audio_pause_pipeline_stage",
            "audio_pause_settings",
            "audio_pipeline",
            "audio_state",
            "audio_types",
        ),
    ),
    "audio_pause_pipeline_detection": contract(
        "audio_pause_pipeline_detection",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_pause_pipeline_stage",
            "audio_pause_settings",
            "audio_pipeline",
            "audio_state",
            "errors",
        ),
    ),
    "audio_pause_pipeline_stage": contract(
        "audio_pause_pipeline_stage",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_external",
            "errors",
            "support",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "audio_processor": contract(
        "audio_processor",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_deps",
            "audio_external",
            "audio_noise_reduction",
            "audio_output_policy",
            "audio_pause_pipeline",
            "audio_pause_pipeline_stage",
            "audio_pause_pipeline_steps",
            "audio_pitch_hum",
            "audio_processor_rendering_portal",
            "audio_processor_runtime",
            "audio_rendering",
            "audio_state",
            "audio_tools",
            "audio_types",
        ),
    ),
    "audio_processor_rendering_portal": contract(
        "audio_processor_rendering_portal",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "audio_types"),
    ),
    "audio_processor_runtime": contract(
        "audio_processor_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_deps",),
    ),
    "audio_recording": contract(
        "audio_recording",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("errors",),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
        notes="Lazy native recorder adapter; Qt/Anki imports stay inside runtime methods.",
    ),
    "audio_rendering": contract(
        "audio_rendering",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_formats",
            "audio_output_policy",
            "audio_pause_pipeline",
            "audio_size_reduction",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "external_command_text",
            "permission_guidance",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_tools": contract(
        "audio_tools",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("error_codes", "errors", "runtime_manager"),
    ),
    "audio_types": contract("audio_types", layer=Layer.IMPORT_SAFE_CORE),
    "ffmpeg_output_contracts": contract(
        "ffmpeg_output_contracts",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors",),
    ),
    "audio_state": contract(
        "audio_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_pause_settings",
            "audio_size_reduction",
            "dpdfnet_settings",
            "editor_history_settings",
            "errors",
            "ffmpeg_defaults",
        ),
    ),
}
