"""Architecture contracts for entrypoint, browser, and settings UI modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

UI_CONTRACTS: dict[str, ModuleContract] = {
    "__init__": contract(
        "__init__",
        layer=Layer.ENTRY_POINT,
        allowed_addon_deps=(
            "_version",
            "browser_integration",
            "config_migration",
            "diagnostics_runtime",
            "editor_integration",
            "ffmpeg_defaults",
            "i18n",
            "release_info",
            "reviewer_integration",
            "reviewer_template_filter_integration",
            "runtime_installer_dialog",
            "runtime_manager",
            "settings",
            "trigger_integration",
            "vendor_runtime",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.ANKI_IMPORTS_MODULE_LEVEL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
            SideEffect.GUI_HOOK_REGISTRATION,
        ),
        allow_module_level_anki_imports=True,
        allow_any_anki_imports=True,
        notes="Bootstrap only: hook registration, menu wiring, and settings entrypoint.",
    ),
    "browser_integration": contract(
        "browser_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processing_presets",
            "audio_state",
            "batch_operations",
            "browser_audio_export_dialog",
            "browser_batch_runner",
            "browser_dialog",
            "diagnostics_runtime",
            "i18n",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.GUI_HOOK_REGISTRATION,
        ),
        allow_any_anki_imports=True,
    ),
    "browser_batch_runner": contract(
        "browser_batch_runner",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_state",
            "batch_operations",
            "browser_result_application",
            "browser_report",
            "diagnostics_runtime",
            "error_codes",
            "i18n",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.MEDIA_WRITE,
            SideEffect.NOTE_UPDATE,
            SideEffect.UNDO_MERGE,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
    ),
    "browser_result_application": contract(
        "browser_result_application",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "batch_operation_types",
            "browser_report",
            "diagnostics_runtime",
            "error_codes",
        ),
        allowed_side_effects=(SideEffect.NOTE_UPDATE,),
    ),
    "browser_audio_export_runner": contract(
        "browser_audio_export_runner",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_export_planning",
            "audio_export_rendering",
            "audio_export_types",
            "audio_export_zip_writer",
            "audio_external",
            "audio_processor",
            "batch_operation_types",
            "error_codes",
            "i18n",
        ),
        allowed_side_effects=(
            SideEffect.BACKGROUND_TASK_DISPATCH,
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_export_zip_writer": contract(
        "audio_export_zip_writer",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_export_planning",
            "audio_export_rendering",
            "audio_export_types",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "browser_audio_export_dialog": contract(
        "browser_audio_export_dialog",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "batch_operation_types",
            "browser_audio_export_runner",
            "browser_audio_export_state",
            "error_codes",
            "external_links",
            "frontend_logs",
            "i18n",
            "webview_bridge",
            "webview_shell",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.WEB_EVAL,
        ),
        allow_any_anki_imports=True,
    ),
    "browser_dialog": contract(
        "browser_dialog",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_operations",
            "batch_operations",
            "browser_dialog_state",
            "browser_report",
            "error_codes",
            "external_links",
            "frontend_logs",
            "i18n",
            "webview_bridge",
            "webview_shell",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.WEB_EVAL,
        ),
        allow_any_anki_imports=True,
    ),
    "browser_dialog_state": contract(
        "browser_dialog_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operation_params",
            "audio_operations",
            "audio_processing_presets",
            "audio_state",
            "batch_operations",
            "browser_report",
            "contracts_generated",
            "i18n",
        ),
    ),
    "browser_audio_export_state": contract(
        "browser_audio_export_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_export_planning",
            "audio_export_types",
            "batch_operation_types",
            "contracts_generated",
            "i18n",
        ),
    ),
    "browser_report": contract(
        "browser_report",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("batch_operations", "i18n"),
    ),
    "reviewer_integration": contract(
        "reviewer_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "editor_actions",
            "editor_callbacks",
            "editor_media",
            "editor_runtime",
            "editor_session",
            "editor_webview_injection",
            "media_paths",
            "reviewer_audio_targets",
            "sound_refs",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.ANKI_IMPORTS_MODULE_LEVEL,
            SideEffect.GUI_HOOK_REGISTRATION,
            SideEffect.NOTE_UPDATE,
            SideEffect.WEB_EVAL,
        ),
        allow_module_level_anki_imports=True,
        allow_any_anki_imports=True,
        notes="Reviewer adapter reuses editor controls and persists note edits from review mode.",
    ),
    "reviewer_template_filter_integration": contract(
        "reviewer_template_filter_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("error_codes", "reviewer_audio_targets", "reviewer_template_filter"),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.ANKI_IMPORTS_MODULE_LEVEL,
            SideEffect.GUI_HOOK_REGISTRATION,
        ),
        allow_module_level_anki_imports=True,
        allow_any_anki_imports=True,
        notes="Template-filter adapter only registers the card-template trigger hook.",
    ),
    "trigger_integration": contract(
        "trigger_integration",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("diagnostics_runtime", "trigger_jobs", "trigger_scheduler"),
        allowed_side_effects=(SideEffect.GUI_HOOK_REGISTRATION,),
    ),
    "trigger_dispatch": contract(
        "trigger_dispatch",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processing_presets",
            "audio_state",
            "batch_operation_types",
            "diagnostics_runtime",
            "trigger_executor",
            "trigger_jobs",
            "trigger_result_application",
        ),
        allowed_side_effects=(SideEffect.BACKGROUND_TASK_DISPATCH,),
        notes="Anki taskman adapter for trigger jobs.",
    ),
    "trigger_executor": contract(
        "trigger_executor",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processing_presets",
            "audio_state",
            "batch_operation_types",
            "browser_batch_runner",
            "diagnostics_runtime",
            "error_codes",
            "trigger_batch_adapter",
            "trigger_jobs",
            "trigger_preset_adapter",
            "trigger_result_application",
            "trigger_state",
        ),
        allowed_side_effects=(SideEffect.MEDIA_WRITE,),
        notes="Per-note trigger execution boundary owns media writes delegated to operation adapters.",
    ),
    "trigger_result_application": contract(
        "trigger_result_application",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "batch_operation_types",
            "diagnostics_runtime",
            "error_codes",
            "trigger_jobs",
            "trigger_state",
        ),
        allowed_side_effects=(SideEffect.ANKI_IMPORTS_ANYWHERE, SideEffect.NOTE_UPDATE),
        allow_any_anki_imports=True,
        notes="Main-thread trigger result application and best-effort Anki refresh notification.",
    ),
    "trigger_runner": contract(
        "trigger_runner",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "trigger_dispatch",
            "trigger_executor",
            "trigger_jobs",
            "trigger_result_application",
            "trigger_scheduler",
        ),
        notes="Compatibility facade for trigger automation entrypoints.",
    ),
    "trigger_scheduler": contract(
        "trigger_scheduler",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=(
            "audio_processing_presets",
            "audio_state",
            "browser_batch_runner",
            "diagnostics_runtime",
            "trigger_dispatch",
            "trigger_jobs",
            "trigger_rules",
            "trigger_state",
        ),
        notes="Trigger rule matching, state scheduling, and dispatch request creation.",
    ),
    "settings": contract(
        "settings",
        layer=Layer.SETTINGS_SHELL,
        allowed_addon_deps=(
            "i18n",
            "runtime_installer_dialog",
            "settings.commands",
            "settings.initial_state",
            "webview_shell",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.ANKI_IMPORTS_MODULE_LEVEL,
            SideEffect.WEB_EVAL,
        ),
        allow_module_level_anki_imports=True,
        allow_any_anki_imports=True,
    ),
    "runtime_installer_dialog": contract(
        "runtime_installer_dialog",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("i18n", "runtime_manager"),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.ANKI_IMPORTS_MODULE_LEVEL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
            SideEffect.THREAD_SPAWN,
        ),
        allow_module_level_anki_imports=True,
        allow_any_anki_imports=True,
    ),
    "settings.commands": contract(
        "settings.commands",
        layer=Layer.SETTINGS_BACKEND,
        allowed_addon_deps=(
            "audio_processing_presets",
            "contracts_generated",
            "diagnostics_runtime",
            "editor_button_visibility",
            "error_codes",
            "external_links",
            "ffmpeg_defaults",
            "frontend_logs",
            "i18n",
            "settings.async_commands",
            "trigger_rules",
            "webview_bridge",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.WEB_EVAL,
        ),
        allow_any_anki_imports=True,
    ),
    "settings.async_commands": contract(
        "settings.async_commands",
        layer=Layer.SETTINGS_BACKEND,
        allowed_addon_deps=(
            "contracts_generated",
            "diagnostics_runtime",
            "error_codes",
            "settings.async_operations",
            "webview_bridge",
        ),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.THREAD_SPAWN,
            SideEffect.WEB_EVAL,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
    ),
    "settings.async_operations": contract(
        "settings.async_operations",
        layer=Layer.SETTINGS_BACKEND,
        allowed_addon_deps=(
            "_version",
            "contracts_generated",
            "db_helpers",
            "diagnostics",
            "diagnostics_runtime",
            "errors",
            "file_reveal",
            "i18n",
            "release_info",
            "runtime_manager",
            "support",
        ),
        allowed_side_effects=(SideEffect.ANKI_IMPORTS_ANYWHERE,),
        allow_any_anki_imports=True,
    ),
    "settings.initial_state": contract(
        "settings.initial_state",
        layer=Layer.SETTINGS_BACKEND,
        allowed_addon_deps=("_version", "i18n", "release_info", "runtime_manager", "settings_state"),
        allowed_side_effects=(SideEffect.ANKI_IMPORTS_ANYWHERE,),
        allow_any_anki_imports=True,
    ),
}
