"""Architecture contracts for audio and batch core modules."""

from __future__ import annotations

from .contract_schema import Layer, ModuleContract, SideEffect, contract

AUDIO_CONTRACTS: dict[str, ModuleContract] = {
    "audio_operations": contract(
        "audio_operations",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "i18n"),
    ),
    "audio_operation_params": contract(
        "audio_operation_params",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_formats", "audio_pause_settings", "audio_state", "dpdfnet_settings"),
    ),
    "audio_pause_settings": contract("audio_pause_settings", layer=Layer.IMPORT_SAFE_CORE),
    "audio_pipeline": contract("audio_pipeline", layer=Layer.IMPORT_SAFE_CORE),
    "audio_artifacts": contract(
        "audio_artifacts",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_pipeline", "audio_state", "audio_tools"),
    ),
    "audio_commands": contract(
        "audio_commands",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_commands_runtime", "audio_formats", "audio_state", "audio_types", "errors"),
    ),
    "audio_commands_runtime": contract(
        "audio_commands_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_commands",),
    ),
    "audio_external": contract(
        "audio_external",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_state", "audio_tools", "diagnostics_runtime", "errors", "permission_guidance"),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "audio_noise_reduction": contract(
        "audio_noise_reduction",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_noise_reduction_bundled",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "support",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "audio_noise_reduction_bundled": contract(
        "audio_noise_reduction_bundled",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "support",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_pitch_hum": contract(
        "audio_pitch_hum",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_pitch_hum_synthesis",
            "audio_pitch_hum_frames",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "permission_guidance",
            "prosody_settings",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_pitch_hum_frames": contract(
        "audio_pitch_hum_frames",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "audio_pitch_hum_synthesis": contract(
        "audio_pitch_hum_synthesis",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_pitch_hum_frames",),
    ),
    "audio_pause_pipeline": contract(
        "audio_pause_pipeline",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_external",
            "audio_pause_pipeline_stage",
            "audio_pause_pipeline_steps",
            "audio_state",
            "audio_tools",
            "audio_types",
            "support",
        ),
    ),
    "audio_pause_pipeline_steps": contract(
        "audio_pause_pipeline_steps",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_external",
            "audio_pause_pipeline_detection",
            "audio_pause_pipeline_stage",
            "audio_pause_settings",
            "audio_pipeline",
            "audio_state",
            "audio_types",
        ),
    ),
    "audio_pause_pipeline_detection": contract(
        "audio_pause_pipeline_detection",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_pause_pipeline_stage",
            "audio_pause_settings",
            "audio_pipeline",
            "audio_state",
            "errors",
        ),
    ),
    "audio_pause_pipeline_stage": contract(
        "audio_pause_pipeline_stage",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_external",
            "errors",
            "support",
        ),
        allowed_side_effects=(SideEffect.SUBPROCESS_RUN,),
    ),
    "audio_processor": contract(
        "audio_processor",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_artifacts",
            "audio_commands",
            "audio_external",
            "audio_noise_reduction",
            "audio_pause_pipeline",
            "audio_pause_pipeline_stage",
            "audio_pause_pipeline_steps",
            "audio_pitch_hum",
            "audio_processor_rendering_portal",
            "audio_processor_runtime",
            "audio_rendering",
            "audio_state",
            "audio_tools",
            "audio_types",
        ),
    ),
    "audio_processor_rendering_portal": contract(
        "audio_processor_rendering_portal",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_processor", "audio_state", "audio_types"),
    ),
    "audio_processor_runtime": contract(
        "audio_processor_runtime",
        layer=Layer.IMPORT_SAFE_CORE,
    ),
    "audio_recording": contract(
        "audio_recording",
        layer=Layer.UI_ADAPTER,
        allowed_addon_deps=("errors",),
        allowed_side_effects=(
            SideEffect.ANKI_IMPORTS_ANYWHERE,
            SideEffect.BACKGROUND_TASK_DISPATCH,
        ),
        allow_any_anki_imports=True,
        notes="Lazy native recorder adapter; Qt/Anki imports stay inside runtime methods.",
    ),
    "audio_rendering": contract(
        "audio_rendering",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_commands",
            "audio_external",
            "audio_formats",
            "audio_pause_pipeline",
            "audio_state",
            "audio_tools",
            "audio_types",
            "errors",
            "permission_guidance",
        ),
        allowed_side_effects=(
            SideEffect.SUBPROCESS_RUN,
            SideEffect.TEMP_FILESYSTEM_CLEANUP,
        ),
    ),
    "audio_tools": contract(
        "audio_tools",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("errors", "runtime_manager"),
    ),
    "audio_types": contract("audio_types", layer=Layer.IMPORT_SAFE_CORE),
    "audio_state": contract(
        "audio_state",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_pause_settings",
            "dpdfnet_settings",
            "errors",
            "ffmpeg_defaults",
        ),
    ),
    "batch_operations": contract(
        "batch_operations",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_operations",
            "audio_processor",
            "audio_state",
            "batch_operation_processing",
            "batch_operation_types",
            "batch_operations_helpers",
            "diagnostics_runtime",
            "errors",
            "media_paths",
            "prosody_cache",
            "sound_refs",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "batch_operation_processing": contract(
        "batch_operation_processing",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=(
            "audio_formats",
            "audio_operation_params",
            "audio_operations",
            "audio_processor",
            "audio_state",
            "batch_operation_types",
            "batch_operations",
            "batch_operations_helpers",
            "diagnostics_runtime",
            "permission_guidance",
            "prosody_svg",
            "sound_refs",
        ),
        allowed_side_effects=(SideEffect.TEMP_FILESYSTEM_CLEANUP,),
    ),
    "batch_operation_types": contract(
        "batch_operation_types",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_operation_params", "audio_operations"),
    ),
    "batch_operations_helpers": contract(
        "batch_operations_helpers",
        layer=Layer.IMPORT_SAFE_CORE,
        allowed_addon_deps=("audio_processor", "audio_state", "audio_types", "batch_operations"),
    ),
}
