#!/usr/bin/env python3
"""Generate typed Python and TypeScript JSON communication contracts."""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMUNICATION_SCHEMA = ROOT / "contracts" / "communication.schema.json"
CONFIG_SCHEMA = ROOT / "addon" / "anki_audio_quick_editor" / "config.schema.json"
SETTINGS_UI_DIR = ROOT / "settings_ui"
TS_OUTPUT = SETTINGS_UI_DIR / "src" / "lib" / "generated" / "contracts.ts"
PY_OUTPUT = ROOT / "addon" / "anki_audio_quick_editor" / "contracts_generated.py"

HEADER_TS = """/* eslint-disable */
// Generated by scripts/generate_contracts.py. Do not edit by hand.

"""
HEADER_PY = '''# mypy: ignore-errors
# ruff: noqa
"""Generated JSON communication contracts. Do not edit by hand."""

'''


@dataclass(frozen=True)
class GeneratedTarget:
    """One generated artifact target."""

    path: Path
    language: str
    header: str
    extra_args: tuple[str, ...]


TARGETS = (
    GeneratedTarget(
        path=TS_OUTPUT,
        language="ts",
        header=HEADER_TS,
        extra_args=("--no-combine-classes", "--just-types"),
    ),
    GeneratedTarget(
        path=PY_OUTPUT,
        language="py",
        header=HEADER_PY,
        extra_args=("--no-combine-classes", "--python-version", "3.7"),
    ),
)


def _quicktype_bin() -> Path:
    binary_name = "quicktype.cmd" if os.name == "nt" else "quicktype"
    return SETTINGS_UI_DIR / "node_modules" / ".bin" / binary_name


def _load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _composed_schema() -> dict[str, object]:
    schema = _load_json(COMMUNICATION_SCHEMA)
    config_schema = _load_json(CONFIG_SCHEMA)
    definitions = schema.get("definitions")
    if not isinstance(definitions, dict):
        raise RuntimeError("communication schema must define a definitions object")

    composed_config = dict(config_schema)
    composed_config.pop("$schema", None)
    composed_config.pop("title", None)
    definitions["Config"] = composed_config
    return schema


def _run_quicktype(quicktype: Path, schema_path: Path, target: GeneratedTarget) -> str:
    command = [
        str(quicktype),
        "--src-lang",
        "schema",
        "--lang",
        target.language,
        "--top-level",
        "CommunicationContracts",
        "--no-date-times",
        *target.extra_args,
        str(schema_path),
    ]
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "quicktype failed")
    content = result.stdout.lstrip()
    if target.language == "py":
        content = _postprocess_python(content)
    return target.header + content


def _postprocess_python(content: str) -> str:
    """Keep quicktype's Python helper compatible with the repository checks."""
    return re.sub(
        r"^([ \t]*)except:\n([ \t]*)pass\n",
        r"\1except (AssertionError, TypeError, ValueError):\n\2pass\n",
        content,
        flags=re.MULTILINE,
    )


def generate_outputs() -> dict[Path, str]:
    """Return generated file contents keyed by repository path."""
    quicktype = _quicktype_bin()
    if not quicktype.exists():
        raise RuntimeError(
            f"quicktype not found at {quicktype}. Run: python3 scripts/dev.py setup"
        )

    with tempfile.TemporaryDirectory() as tmp:
        schema_path = Path(tmp) / "communication.composed.schema.json"
        schema_path.write_text(
            json.dumps(_composed_schema(), indent=2, sort_keys=True),
            encoding="utf-8",
        )
        return {target.path: _run_quicktype(quicktype, schema_path, target) for target in TARGETS}


def stale_targets(generated: dict[Path, str]) -> list[Path]:
    """Return generated target paths whose committed content is missing or stale."""
    stale: list[Path] = []
    for path, content in generated.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
    return stale


def write_outputs(generated: dict[Path, str]) -> None:
    """Write generated contract artifacts to disk."""
    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _print_diff(path: Path, expected: str) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    rel = path.relative_to(ROOT)
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{rel} (current)",
        tofile=f"{rel} (generated)",
    )
    sys.stdout.writelines(diff)


def check_outputs(generated: dict[Path, str]) -> int:
    """Return nonzero when generated artifacts are stale."""
    stale = stale_targets(generated)
    if not stale:
        print("Generated communication contracts are up to date.")
        return 0

    print("Generated communication contracts are stale. Run:")
    print("  python3 scripts/dev.py contracts-generate")
    for path in stale:
        print()
        _print_diff(path, generated[path])
    return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated contract files")
    mode.add_argument("--check", action="store_true", help="check generated files are current")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        generated = generate_outputs()
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.write:
        write_outputs(generated)
        for path in generated:
            print(f"wrote {path.relative_to(ROOT)}")
        return 0
    return check_outputs(generated)


if __name__ == "__main__":
    raise SystemExit(main())
