"""External denoise and voice-only extraction orchestration."""

from __future__ import annotations

import shutil
import subprocess  # nosec B404
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

from . import audio_noise_reduction_bundled as _bundled
from .audio_commands import (
    build_deep_filter_command,
    build_deep_filter_prepare_command,
    build_mp3_encode_command,
)
from .audio_external import (
    _run_external_command,
    probe_duration_ms,
)
from .audio_state import AudioProcessingConfig
from .audio_tools import (
    find_deep_filter,
    find_ffmpeg,
)
from .audio_types import AudioProcessingResult
from .errors import AudioProcessingError


def select_deep_filter_output(output_dir: Path) -> Path:
    """Return the single WAV generated by DeepFilterNet, or raise a clear error."""
    wav_outputs = sorted(path for path in output_dir.glob("*.wav") if path.is_file())
    if len(wav_outputs) == 1:
        return wav_outputs[0]
    if not wav_outputs:
        raise AudioProcessingError("DeepFilterNet did not produce a WAV output.")
    raise AudioProcessingError("DeepFilterNet produced multiple WAV outputs.")


def render_noise_reduced_audio(
    source_path: Path,
    config: AudioProcessingConfig,
    output_path: Path | None = None,
    on_command: Callable[[tuple[str, ...]], None] | None = None,
) -> AudioProcessingResult:
    """Render a noise-reduced MP3 using the external DeepFilterNet executable."""
    ffmpeg_path = find_ffmpeg(config.ffmpeg_path)
    deep_filter_path = find_deep_filter()
    if output_path is None:
        output_path = Path(tempfile.mkstemp(prefix="aqe_denoised_", suffix=".mp3")[1])

    work_dir = Path(tempfile.mkdtemp(prefix="aqe_deep_filter_"))
    input_wav = work_dir / "input_48k_mono.wav"
    deep_filter_output_dir = work_dir / "deep_filter_output"
    deep_filter_output_dir.mkdir(parents=True, exist_ok=True)

    try:
        prepare_cmd = build_deep_filter_prepare_command(ffmpeg_path, source_path, input_wav)
        _run_audio_stage(
            prepare_cmd,
            "Could not start audio preparation for DeepFilterNet.",
            "Could not prepare audio for DeepFilterNet.",
            on_command,
        )

        deep_filter_cmd = build_deep_filter_command(
            deep_filter_path,
            input_wav,
            deep_filter_output_dir,
            post_filter=config.deep_filter_post_filter,
        )
        _run_audio_stage(
            deep_filter_cmd,
            "Could not start DeepFilterNet noise removal.",
            "DeepFilterNet noise removal failed.",
            on_command,
        )

        cleaned_wav = select_deep_filter_output(deep_filter_output_dir)
        encode_cmd = build_mp3_encode_command(ffmpeg_path, cleaned_wav, output_path)
        _run_audio_stage(
            encode_cmd,
            "Could not start MP3 encoding for DeepFilterNet output.",
            "Could not encode DeepFilterNet output.",
            on_command,
        )

        return AudioProcessingResult(
            output_path=output_path,
            command=deep_filter_cmd,
            duration_ms=probe_duration_ms(output_path, config),
        )
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def _run_audio_stage(
    command: tuple[str, ...],
    launch_error: str,
    failure_message: str,
    on_command: Callable[[tuple[str, ...]], None] | None,
) -> subprocess.CompletedProcess[str]:
    if on_command:
        on_command(command)
    result = _run_external_command(command, launch_error)
    if result.returncode != 0:
        raise AudioProcessingError(result.stderr.strip() or failure_message)
    return result


render_rnnoise_audio = _bundled.render_rnnoise_audio
render_dpdfnet_audio = _bundled.render_dpdfnet_audio
render_voice_only_audio = _bundled.render_voice_only_audio


def _bundled_member(name: str) -> Any:
    return getattr(_bundled, name)


def _run_recorded_external_command(*args: Any, **kwargs: Any) -> Any:
    runner = _bundled_member("_run_recorded_external_command")
    return runner(*args, **kwargs)


def _record_rnnoise_failure(*args: Any, **kwargs: Any) -> Any:
    recorder = _bundled_member("_record_rnnoise_failure")
    return recorder(*args, **kwargs)
