"""DeepFilterNet and RNNoise denoise orchestration."""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from collections.abc import Callable
from pathlib import Path

from .audio_commands import (
    build_deep_filter_command,
    build_deep_filter_prepare_command,
    build_mp3_encode_command,
    build_rnnoise_command,
    build_rnnoise_encode_command,
    build_rnnoise_prepare_command,
)
from .audio_external import (
    _render_external_error_message,
    _run_external_command,
    probe_duration_ms,
)
from .audio_state import AudioProcessingConfig
from .audio_tools import find_deep_filter, find_ffmpeg, find_rnnoise_bundle
from .audio_types import AudioProcessingResult
from .errors import AudioProcessingError
from .support import build_command_record, record_latest_rnnoise_support_incident


def select_deep_filter_output(output_dir: Path) -> Path:
    """Return the single WAV generated by DeepFilterNet, or raise a clear error."""
    wav_outputs = sorted(path for path in output_dir.glob("*.wav") if path.is_file())
    if len(wav_outputs) == 1:
        return wav_outputs[0]
    if not wav_outputs:
        raise AudioProcessingError("DeepFilterNet did not produce a WAV output.")
    raise AudioProcessingError("DeepFilterNet produced multiple WAV outputs.")


def render_noise_reduced_audio(
    source_path: Path,
    config: AudioProcessingConfig,
    output_path: Path | None = None,
    on_command: Callable[[tuple[str, ...]], None] | None = None,
) -> AudioProcessingResult:
    """Render a noise-reduced MP3 using the external DeepFilterNet executable."""
    ffmpeg_path = find_ffmpeg(config.ffmpeg_path)
    deep_filter_path = find_deep_filter(config.deep_filter_path)
    if output_path is None:
        output_path = Path(tempfile.mkstemp(prefix="aqe_denoised_", suffix=".mp3")[1])

    work_dir = Path(tempfile.mkdtemp(prefix="aqe_deep_filter_"))
    input_wav = work_dir / "input_48k_mono.wav"
    deep_filter_output_dir = work_dir / "deep_filter_output"
    deep_filter_output_dir.mkdir(parents=True, exist_ok=True)

    try:
        prepare_cmd = build_deep_filter_prepare_command(ffmpeg_path, source_path, input_wav)
        _run_audio_stage(
            prepare_cmd,
            "Could not start audio preparation for DeepFilterNet.",
            "Could not prepare audio for DeepFilterNet.",
            on_command,
        )

        deep_filter_cmd = build_deep_filter_command(
            deep_filter_path,
            input_wav,
            deep_filter_output_dir,
            post_filter=config.deep_filter_post_filter,
        )
        _run_audio_stage(
            deep_filter_cmd,
            "Could not start DeepFilterNet noise removal.",
            "DeepFilterNet noise removal failed.",
            on_command,
        )

        cleaned_wav = select_deep_filter_output(deep_filter_output_dir)
        encode_cmd = build_mp3_encode_command(ffmpeg_path, cleaned_wav, output_path)
        _run_audio_stage(
            encode_cmd,
            "Could not start MP3 encoding for DeepFilterNet output.",
            "Could not encode DeepFilterNet output.",
            on_command,
        )

        return AudioProcessingResult(
            output_path=output_path,
            command=deep_filter_cmd,
            duration_ms=probe_duration_ms(output_path, config),
        )
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def _run_audio_stage(
    command: tuple[str, ...],
    launch_error: str,
    failure_message: str,
    on_command: Callable[[tuple[str, ...]], None] | None,
) -> subprocess.CompletedProcess[str]:
    if on_command:
        on_command(command)
    result = _run_external_command(command, launch_error)
    if result.returncode != 0:
        raise AudioProcessingError(result.stderr.strip() or failure_message)
    return result


def render_rnnoise_audio(
    source_path: Path,
    config: AudioProcessingConfig,
    output_path: Path | None = None,
    on_command: Callable[[tuple[str, ...]], None] | None = None,
) -> AudioProcessingResult:
    """Render a denoised MP3 using the bundled RNNoise executable."""
    ffmpeg_path: Path | None = None
    rnnoise_path: Path | None = None
    attempted_commands: list[dict[str, object]] = []
    work_dir: Path | None = None
    try:
        ffmpeg_path = find_ffmpeg(config.ffmpeg_path)
        rnnoise_path = find_rnnoise_bundle()
        if output_path is None:
            output_path = Path(tempfile.mkstemp(prefix="aqe_rnnoise_", suffix=".mp3")[1])

        work_dir = Path(tempfile.mkdtemp(prefix="aqe_rnnoise_"))
        input_raw = work_dir / "input_48k_mono.s16le"
        denoised_raw = work_dir / "denoised.s16le"

        prepare_cmd = build_rnnoise_prepare_command(ffmpeg_path, source_path, input_raw)
        prepare_result = _run_recorded_external_command(
            prepare_cmd,
            "Could not start audio preparation for RNNoise.",
            attempted_commands,
            on_command,
        )
        if prepare_result.returncode != 0:
            raise AudioProcessingError(
                _render_external_error_message(
                    prepare_result,
                    "Could not prepare audio for RNNoise.",
                )
            )

        rnnoise_cmd = build_rnnoise_command(rnnoise_path, input_raw, denoised_raw)
        rnnoise_result = _run_recorded_external_command(
            rnnoise_cmd,
            "Could not start RNNoise denoise.",
            attempted_commands,
            on_command,
        )
        if rnnoise_result.returncode != 0:
            raise AudioProcessingError(
                _render_external_error_message(rnnoise_result, "RNNoise denoise failed.")
            )
        if not denoised_raw.is_file():
            raise AudioProcessingError("RNNoise did not produce a raw PCM output.")

        encode_cmd = build_rnnoise_encode_command(ffmpeg_path, denoised_raw, output_path)
        encode_result = _run_recorded_external_command(
            encode_cmd,
            "Could not start MP3 encoding for RNNoise output.",
            attempted_commands,
            on_command,
        )
        if encode_result.returncode != 0:
            raise AudioProcessingError(
                _render_external_error_message(
                    encode_result,
                    "Could not encode RNNoise output.",
                )
            )

        return AudioProcessingResult(
            output_path=output_path,
            command=rnnoise_cmd,
            duration_ms=probe_duration_ms(output_path, config),
        )
    except Exception as exc:
        _record_rnnoise_failure(
            source_path,
            exc,
            ffmpeg_path=ffmpeg_path,
            rnnoise_path=rnnoise_path,
            attempted_commands=attempted_commands,
        )
        raise
    finally:
        if work_dir is not None:
            shutil.rmtree(work_dir, ignore_errors=True)


def _run_recorded_external_command(
    command: tuple[str, ...],
    launch_error_message: str,
    attempted_commands: list[dict[str, object]],
    on_command: Callable[[tuple[str, ...]], None] | None,
) -> subprocess.CompletedProcess[str]:
    if on_command:
        on_command(command)
    try:
        result = _run_external_command(command, launch_error_message)
    except AudioProcessingError as exc:
        attempted_commands.append(build_command_record(command, launch_error=str(exc)))
        raise
    attempted_commands.append(
        build_command_record(
            command,
            returncode=result.returncode,
            stdout=result.stdout,
            stderr=result.stderr,
        )
    )
    return result


def _record_rnnoise_failure(
    source_path: Path,
    exc: Exception,
    *,
    ffmpeg_path: Path | None,
    rnnoise_path: Path | None,
    attempted_commands: list[dict[str, object]],
) -> None:
    record_latest_rnnoise_support_incident(
        operation="rnnoise_denoise",
        media_filename=source_path.name,
        source_path=str(source_path.resolve()),
        user_message=str(exc),
        exception_type=type(exc).__name__,
        ffmpeg_path=str(ffmpeg_path) if ffmpeg_path is not None else "",
        rnnoise_path=str(rnnoise_path) if rnnoise_path is not None else "",
        attempted_commands=attempted_commands,
    )

